### ISSUE TITLE
【help】运行出错，还请协助，谢谢

### ISSUE THREAD

**Issue by justincnn** [tengfei-xy/amazon-crawler#1]
在linux下运行：
部分配置如下：
~~~yaml
basic:
  # 相同主机下的app标识
  app_id: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.95 Safari/537.36

  # 不同相同主机的标识
  # 相同主机下host_id应相同，但倘若使用了socks5，请检查cookie本身是否适用于对应的代理服务器
  # 主要用来标识相同的主机下应使用相同的cookie，当然，其实不同的cookie也是可以的。
  host_id: session-id=130-2207123090-6197955; session-id-time=20827
~~~

错误提示：
~~~bash
panic: yaml: unmarshal errors:
  line 3: cannot unmarshal !!str `Mozilla...` into int
  line 8: cannot unmarshal !!str `session...` into int

goroutine 1 [running]:
main.init_config({{0x7ffdd6c08816?, 0x60?}, 0x0?})
        amazon-crawler/main.go:71 +0x117
main.main()
        amazon-crawler/main.go:129 +0x1e
~~~

**Comment by tengfei-xy** [comment]
app_id和host_id是对于数据库的标识，如果你只有一个爬虫端，都设置为1即可，cookie是来自mysql的，代码：`app.db.QueryRow("select cookie from cookie where host_id = ?", app.Basic.Host_id).Scan(&cookie);`

**Comment by tengfei-xy** [comment]
mysql> select host_id,cookie from cookie;
+---------+------------------------------------+
| host_id | cookie                             |
+---------+------------------------------------+
|       1 | xxxxxxxxxxxxxxxxxxxx=xxxxxxxxxxxxx |
+---------+------------------------------------+
1 row in set (0.00 sec)

**Comment by tengfei-xy** [comment]
User Agent用了默认的，无法通过配置修改，有需要的话，从源码中改，search.go，sell.go，trn.go都有

**Comment by tengfei-xy** [comment]
配置文件的配发，参考https://github.com/tengfei-xy/amazon-crawler/blob/main/config.yaml.save
